---
resource_types:
  - name: docker-image-resource
    type: docker-image
    privileged: true
    source:
       insecure_registries: ["docker.egira.saab.se:5000"]
       repository: docker.egira.saab.se:5000/docker-image-resource
       tag: v0.0.15

resources:

  - name: semver-resource
    type: git
    source:
       uri: ((git-repo))
       branch: ((git-branch))
       private_key: ((private_repo_key))
       check_every: 5s

  - name: semver-resource-image
    type: docker-image-resource
    source:
       insecure_registries: ["((registry))"]
       repository: ((registry))/semver-resource-image
       username: {{registry-user}}
       password: {{registry-password}}

jobs:
- name: build-echo-server-image
  plan:
     - get: semver-resource
       trigger: true
     - put: semver-resource-image
       params:
         build: semver-resource
